config/routes.rb
Rails.application.routes.draw do
  get 'yellow/index'
  post 'yellow/create'
  resources :column do
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/column.rb
class Column < ApplicationRecord
    validates :title, presence: true
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/card_controller.rb
class CardController < ApplicationController
        def create
            @card = Card.new(card_params)
      end
      def destroy
        @card = Card.find(params[:id])
        @card.destroy
      end
end

app/controllers/column_controller.rb
class ColumnController < ApplicationController
    def show
        @card = Card.find(params[:id])
      end
      def destroy
        @column = Column.find(params[:id])
        @column.destroy
    
        redirect_to yellow_index_url
      end   
end

app/controllers/yellow_controller.rb
class YellowController < ApplicationController
  def index
    @columns = Column.all


  end
  def show
    @column = Column.find(params[:id])
  end  
  def new
    @column = Column.new
  end  
  def create
    # render plain: params.inspect
    @column = Column.new(column_params)
    if @column.save
      redirect_to yellow_index_url
    else
      render 'index'
    end
  end 
  def destroy
    @column = Column.find(params[:id])
    @column.destroy

    redirect_to yellow_index_url
  end   
  private
        def column_params
          params.permit(:title)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/column_helper.rb
module ColumnHelper
end

app/helpers/yellow_helper.rb
module YellowHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Yellow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/yellow/index.html.erb
<center>
<h1 style="color:lightblue;font-family:Helvetica"> Yello</h1></center>
<div class="container">
<h2>To do</h2>
    <div id="sortable">
   
<% @columns.each do |column| %>

    <div class="column"><%= column.title %><br>
    <%= button_to 'Delete', column_path(column),
    method: :delete %></div>
    <% end %></div>
    <%= form_with model: @column,url:yellow_create_url, local: true do |form| %>
        <p>
         <%= form.label :"Card Text" %> 
        <%= form.text_field :title %>
        </p>
        <p>
        <%= form.submit "Add Card" %>
        </p>
    </div>
    <div id="sortable">
   
    <% @columns.each do |column| %>
    
        <div class="column"><%= column.title %><br>
        <%= button_to 'Delete', column_path(column),
        method: :delete %></div>
        <% end %></div>
        <%= form_with model: @column,url:yellow_create_url, local: true do |form| %>
            <p>
             <%= form.label :"Card Text" %> 
            <%= form.text_field :title %>
            </p>
            <p>
            <%= form.submit "Add Card" %>
            </p>
        </div>
        <% end %>




<% end %>